server:
  port: 9006
spring:
  application:
    name: hrm-page
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_page
      username: root
      password: 334455
mybatis-plus:
  mapper-locations: classpath:xpc/com/hrm/mapper/*Mapper.xml
  type-aliases-package: com.xpc.hrm.domain,com.xpc.hrm.query